/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ateebahmed.showcase.userprofiles.app;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication(scanBasePackages = "com.ateebahmed.showcase.userprofiles.app.features.basicinfo.infrastructure.mapper.*")
public class App {
    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
